# Generated by Django 4.2.20 on 2025-03-27 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrn', models.CharField(max_length=10, unique=True)),
                ('make', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=25)),
                ('engineCapacity', models.CharField(max_length=25)),
                ('fuelType', models.CharField(max_length=25)),
                ('yearOfManufacture', models.CharField(max_length=4)),
                ('colour', models.CharField(max_length=15)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
