# Generated by Django 4.2.20 on 2025-03-27 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='engineCapacity',
            new_name='engine_capacity',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='fuelType',
            new_name='fuel_type',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='yearOfManufacture',
            new_name='year_of_manufacture',
        ),
    ]
