# Generated by Django 4.2.20 on 2025-03-27 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0002_rename_enginecapacity_vehicle_engine_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('approved', models.BooleanField(default=False)),
                ('booking_type', models.CharField(choices=[('Service', 'Service'), ('MOT', 'MOT'), ('Repair', 'Repair'), ('Other', 'Other')], max_length=10)),
                ('customer_notes', models.TextField(max_length=1000)),
                ('mechanics_notes', models.TextField(max_length=1000)),
                ('vehicle_mileage_at_service', models.PositiveIntegerField()),
                ('completed_service', models.BooleanField(default=False)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='vehicles.vehicle')),
            ],
        ),
    ]
